#!/usr/bin/env python3
"""
Convert HDFC bank statement PDF to CSV.

Requires poppler-utils (pdftotext) on PATH.

Usage:
    python scripts/hdfc-pdf-to-csv.py "HDFC 2024-2025 Statement_unlocked.pdf"
    python scripts/hdfc-pdf-to-csv.py input.pdf -o output.csv
"""

from __future__ import annotations

import argparse
import csv
import re
import shutil
import subprocess
import sys
from pathlib import Path

TX_LINE = re.compile(
    r"^\s*(\d{2}/\d{2}/\d{2})\s+(.+)\s+"
    r"(0\d{14,16}|N\d+|CMS\d+|MIR\d+)\s+"
    r"(\d{2}/\d{2}/\d{2})\s+"
    r"(.*)$"
)
CONT_LINE = re.compile(r"^\s{10,}(.+)$")
AMOUNT_RE = re.compile(r"[\d,]+\.\d{2}")
UPI_REF_RE = re.compile(r"-(\d{10,})-UPI", re.IGNORECASE)
MOBILE_REF_RE = re.compile(r"-(\d{10})@(AXL|YBL)", re.IGNORECASE)
OKBIZ_REF_RE = re.compile(r"(\d{10})@OKBIZ", re.IGNORECASE)
FT_ACCOUNT_RE = re.compile(r"-(\d{10,})\s*-")
IMPS_DATE_RE = re.compile(r"#(\d{2})/(\d{2})/(\d{4})\s+(\d{6})")

CONT_STOP_MARKERS = (
    "STATEMENT SUMMARY",
    "Opening Balance",
    "Dr Count",
    "Generated On:",
    "Generated By:",
    "HDFC BANK LIMITED",
    "Closing balance includes",
    "Registered Office Address",
)

SKIP_MARKERS = (
    "Page No",
    "Statement of account",
    "MS. MEDHA",
    "HDFC BANK",
    "Closing balance",
    "***",
    "Date",
    "Narration",
    "Chq./Ref",
    "Withdrawal Amt",
    "Deposit Amt",
    "Closing Balance",
    "Value Dt",
)


def parse_amount(value: str) -> float:
    if not value:
        return 0.0
    return float(value.replace(",", ""))


def format_amount(value: float) -> str:
    if value == 0:
        return ""
    if value == int(value):
        return str(int(value))
    return f"{value:.2f}".rstrip("0").rstrip(".")


def should_skip(line: str) -> bool:
    if "From :" in line and "To :" in line:
        return True
    return any(marker in line for marker in SKIP_MARKERS)


def normalize_description(parts: list[str]) -> str:
    description = " ".join(part.strip() for part in parts if part.strip())
    description = re.sub(r"\s+", " ", description).strip()
    return description


def extract_reference(description: str, chq_ref: str) -> str:
    upper = description.upper()
    compact = re.sub(r"\s+", "", description)

    if (
        upper.startswith("NEFT CR")
        or upper.startswith("NEFT DR")
        or upper.startswith("NEFTCR")
        or upper.startswith("NEFTDR")
    ):
        return ""

    if upper.startswith("FT-") or upper.startswith("FT "):
        ft_match = FT_ACCOUNT_RE.search(description)
        if ft_match:
            return ft_match.group(1)

    if ".IMPS P2P" in upper or ".IMPSP2P" in compact.upper():
        date_match = IMPS_DATE_RE.search(description)
        if date_match:
            day, month, year, suffix = date_match.groups()
            return f"{year}{day}{month}{suffix[-2:]}"

    gpay_match = re.search(r"GPAY-(\d{8,})", description, re.IGNORECASE)
    if gpay_match:
        return gpay_match.group(1)

    okbiz_match = OKBIZ_REF_RE.search(compact)
    if okbiz_match:
        return okbiz_match.group(1)

    mobile_match = MOBILE_REF_RE.search(description)
    if mobile_match:
        return mobile_match.group(1)

    upi_match = UPI_REF_RE.search(compact)
    if upi_match:
        return upi_match.group(1)

    if chq_ref.startswith("N"):
        return ""

    return chq_ref.lstrip("0") or "0"


def classify_amounts(
    narr_start: str, _line: str, _value_date: str, tail: str
) -> tuple[str, str, str]:
    amounts = AMOUNT_RE.findall(tail)
    if not amounts:
        return "", "", ""

    balance = amounts[-1]
    if len(amounts) == 1:
        return "", "", balance

    txn_amount = amounts[0]
    is_upi = narr_start.strip().upper().startswith("UPI-")

    if is_upi:
        return txn_amount, "", balance

    return "", txn_amount, balance


def extract_pdf_text(pdf_path: Path) -> str:
    pdftotext = shutil.which("pdftotext")
    if not pdftotext:
        raise RuntimeError(
            "pdftotext not found. Install poppler-utils "
            "(e.g. apt install poppler-utils)."
        )

    result = subprocess.run(
        [pdftotext, "-layout", str(pdf_path), "-"],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout


def parse_transactions(text: str) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    current: dict | None = None

    for raw_line in text.splitlines():
        line = raw_line.replace("\f", "")
        if not line.strip() or should_skip(line):
            continue

        tx_match = TX_LINE.match(line)
        if tx_match:
            if current:
                rows.append(current)

            date, narr_start, chq_ref, value_date, tail = tx_match.groups()
            withdrawal_raw, deposit_raw, balance_raw = classify_amounts(
                narr_start, line, value_date, tail
            )

            current = {
                "date": date,
                "narr_parts": [narr_start.strip()],
                "chq_ref": chq_ref.strip(),
                "value_date": value_date,
                "withdrawal": format_amount(parse_amount(withdrawal_raw)),
                "deposit": format_amount(parse_amount(deposit_raw)),
                "balance": format_amount(parse_amount(balance_raw)),
            }
            continue

        cont_match = CONT_LINE.match(line)
        if cont_match and current:
            part = cont_match.group(1).strip()
            if any(marker in line for marker in CONT_STOP_MARKERS):
                rows.append(current)
                current = None
                continue
            if part and not re.match(r"^\d{2}/\d{2}/\d{2}\b", part):
                current["narr_parts"].append(part)

    if current:
        rows.append(current)

    transactions: list[dict[str, str]] = []
    for row in rows:
        description = normalize_description(row["narr_parts"])
        transactions.append(
            {
                "Date": row["date"],
                "Description": description,
                "Reference": extract_reference(description, row["chq_ref"]),
                "Value Date": row["value_date"],
                "Withdrawal": row["withdrawal"],
                "Deposit": row["deposit"],
                "Balance": row["balance"],
            }
        )

    return transactions


def default_output_path(pdf_path: Path) -> Path:
    stem = pdf_path.stem.replace(" ", "_").replace("-", "_")
    return pdf_path.with_name(f"{stem}.csv")


def write_csv(transactions: list[dict[str, str]], output_path: Path) -> None:
    fieldnames = [
        "Date",
        "Description",
        "Reference",
        "Value Date",
        "Withdrawal",
        "Deposit",
        "Balance",
    ]
    with output_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(transactions)


def convert(pdf_path: Path, output_path: Path) -> int:
    text = extract_pdf_text(pdf_path)
    transactions = parse_transactions(text)
    if not transactions:
        raise RuntimeError(f"No transactions found in {pdf_path}")

    write_csv(transactions, output_path)
    return len(transactions)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Convert an HDFC bank statement PDF into CSV."
    )
    parser.add_argument("pdf", type=Path, help="Path to the HDFC statement PDF")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help="Output CSV path (default: same name as PDF with .csv extension)",
    )
    args = parser.parse_args()

    pdf_path = args.pdf.expanduser().resolve()
    if not pdf_path.is_file():
        print(f"Error: PDF not found: {pdf_path}", file=sys.stderr)
        return 1

    output_path = (
        args.output.expanduser().resolve()
        if args.output
        else default_output_path(pdf_path)
    )

    try:
        count = convert(pdf_path, output_path)
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    print(f"Wrote {count} transactions to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
